### ISSUE TITLE
add roadmap to readme

### ISSUE THREAD

**Issue by trkaplan** [citydaoproject/contracts-template#16]
@tippi-fifestarr suggested adding this roadmap to the contracts-template repo. 

**Related Task:** [Adding context to readme.md](https://app.dework.xyz/citydao/engineering-2?taskId=4828c0f6-7dd9-4e2c-b1ae-dcc216c12e49)
**Related PR:** https://github.com/citydaoproject/contracts-template/pull/10

I've added my notes: 

**Proposed Roadmap:**

- [x] Update readme 
- [x] Go to CityDAO Dev Guild meeting `Removed, since I find this is not a part of the projects own roadmap.`
- [ ] Add Additional Templates w/ Examples `Removed. Another template will be added when another type of project we're going to build. But thanks for noting this.`
- [ ] Update template `Keeping the codebase updated is a common thing for all the repos.`
- [ ] Live workshop demo video on YouTube `Good idea! `
    - [ ] English
    - [ ] Chinese `English is enough IMO since we expect the developers we want to reach are already comfortable with English. `
